### ISSUE TITLE
Problemas en la ventana de Registro 

### ISSUE THREAD

**Issue by josedu2a** [LosSietePecadosCapitales/JuegoDeCartas#1]
Al testear se encontraron los siguientes problemas:
- Funcionalidad incorrecta en los **botones** para **retroceder** a la ventana anterior, **minimizar** y **cerrar** aplicación.
- Visibilidad de la contraseña en los **campos** de **Contraseña** y **confirmar contraseña**

Capturas:
![Screenshot 03-05-2021 23_34_00](https://user-images.githubusercontent.com/68288650/116958917-14c68f00-ac6a-11eb-9c2f-e59824059b14.png)
![Screenshot 03-05-2021 23_45_51](https://user-images.githubusercontent.com/68288650/116958945-2445d800-ac6a-11eb-999a-49c88e59b9f7.png)

**Comment by paralelogramo** [comment]
Arreglado, métodos agregados.
